export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME='spaceship'
export SPACESHIP_CHAR_SYMBOL='> '
SPACESHIP_PROMPT_ORDER=(
  time          # Time stampts section
  user          # Username section
  dir           # Current directory section
  host          # Hostname section
  git           # Git section (git_branch + git_status)
  # hg            # Mercurial section (hg_branch  + hg_status)
  package       # Package version
  node          # Node.js section
  ruby          # Ruby section
  elixir        # Elixir section
  xcode         # Xcode section
  swift         # Swift section
  golang        # Go section
  php           # PHP section
  rust          # Rust section
  haskell       # Haskell Stack section
  julia         # Julia section
  docker        # Docker section
  aws           # Amazon Web Services section
  venv          # virtualenv section
  conda         # conda virtualenv section
  pyenv         # Pyenv section
  dotnet        # .NET section
  ember         # Ember.js section
  exec_time     # Execution time
  line_sep      # Line break
  battery       # Battery level and status
  vi_mode       # Vi-mode indicator
  jobs          # Background jobs indicator
  exit_code     # Exit code section
  char          # Prompt character
)
plugins=(
  colored-man-pages
  colorize
  command-not-found
  cp
  git
  history
  tmux
  zsh-autosuggestions
  zsh-syntax-highlighting
  # zsh-z
  z
)
source $ZSH/oh-my-zsh.sh

alias tmux='tmux -2' # force tmux 256 color for proper ZENBURN!!!! BURN!!!!!!!

export EDITOR='nvim'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_DEFAULT_COMMAND='fd -tf'
export PATH="$HOME/.cargo/bin:$HOME/go/bin:$PATH"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
